env: "dev"

db_host: "127.0.0.1"
db_port: "3306"
db_user: "root"
db_password: "tanish@123"
db_name: "students_db"
database_url: "root:@tcp(127.0.0.1:3306)/students_db?parseTime=true"

http_server:
  address: "localhost:8082"